# Generated by Django 2.2.16 on 2021-09-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210913_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='user', max_length=10, verbose_name='Роль пользователя'),
        ),
    ]
